-- DIGITAL WORLD VIP - ESQUEMA SUPABASE
-- Ejecutar en Supabase > SQL Editor > New query.

create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  id int primary key default 1 check (id=1),
  academy_name text not null default 'Digital World VIP',
  whatsapp text default '',
  hero_title text default 'Aprende a crear y vender productos digitales',
  hero_subtitle text default 'Una academia práctica para desarrollar habilidades y construir nuevas fuentes de ingresos por internet.',
  about_text text default 'Capacitación paso a paso, recursos descargables y contenido organizado por membresía.',
  transfer_details text default 'Configura aquí tus datos de transferencia desde el panel administrador.',
  updated_at timestamptz default now()
);
insert into public.site_settings(id) values(1) on conflict do nothing;

create table if not exists public.plans (
  slug text primary key,
  name text not null,
  description text default '',
  price_local numeric(12,2) default 0,
  price_usd numeric(12,2) default 0,
  features text[] default '{}',
  curriculum text[] default '{}',
  level int not null,
  active boolean default true
);
insert into public.plans(slug,name,description,features,curriculum,level) values
('bronce','Bronce','Base para comenzar desde cero.',array['Fundamentos del negocio digital','Creación de tu primera oferta','Recursos de inicio'],array['Introducción al ecosistema digital','Definición del producto digital','Primeros pasos para vender en internet'],1),
('oro','Oro','Formación intermedia para desarrollar tu sistema de ventas.',array['Estrategia de contenidos','Embudo y conversión','Recursos avanzados'],array['Diseño de oferta','Contenido y captación','Proceso de conversión'],2),
('diamante','Diamante','Programa premium con contenido exclusivo.',array['Programa completo','Biblioteca premium','Material exclusivo'],array['Estrategia integral','Optimización y escalamiento','Recursos premium'],3)
on conflict(slug) do nothing;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text default '',
  email text default '',
  role text not null default 'student' check(role in ('admin','student')),
  plan_slug text references public.plans(slug),
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.founders (
  id bigint generated by default as identity primary key,
  name text not null,
  role text default 'Co-fundador',
  bio text default '',
  photo_url text default '',
  sort_order int default 0
);
insert into public.founders(name,role,bio,sort_order)
select 'Fundador '||n,'Co-fundador','Agrega aquí la biografía y especialidad.',n from generate_series(1,4)n
where not exists(select 1 from public.founders);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  plan_slug text not null references public.plans(slug) on delete cascade,
  title text not null,
  description text default '',
  sort_order int default 0,
  created_at timestamptz default now()
);
create table if not exists public.lessons (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(id) on delete cascade,
  title text not null,
  description text default '',
  video_path text,
  file_path text,
  sort_order int default 0,
  published boolean default true,
  created_at timestamptz default now()
);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and active=true);
$$;
create or replace function public.my_plan() returns text language sql stable security definer set search_path=public as $$
  select plan_slug from public.profiles where id=auth.uid() and active=true;
$$;

alter table public.site_settings enable row level security;
alter table public.plans enable row level security;
alter table public.founders enable row level security;
alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;

drop policy if exists "public settings read" on public.site_settings; create policy "public settings read" on public.site_settings for select using(true);
drop policy if exists "public plans read" on public.plans; create policy "public plans read" on public.plans for select using(active=true or public.is_admin());
drop policy if exists "public founders read" on public.founders; create policy "public founders read" on public.founders for select using(true);
drop policy if exists "admin settings write" on public.site_settings; create policy "admin settings write" on public.site_settings for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin plans write" on public.plans; create policy "admin plans write" on public.plans for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "admin founders write" on public.founders; create policy "admin founders write" on public.founders for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "own profile read" on public.profiles; create policy "own profile read" on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
drop policy if exists "admin profile write" on public.profiles; create policy "admin profile write" on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "course access" on public.courses; create policy "course access" on public.courses for select to authenticated using(public.is_admin() or plan_slug=public.my_plan());
drop policy if exists "course admin write" on public.courses; create policy "course admin write" on public.courses for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "lesson access" on public.lessons; create policy "lesson access" on public.lessons for select to authenticated using(public.is_admin() or exists(select 1 from public.courses c where c.id=course_id and c.plan_slug=public.my_plan()));
drop policy if exists "lesson admin write" on public.lessons; create policy "lesson admin write" on public.lessons for all to authenticated using(public.is_admin()) with check(public.is_admin());

grant select on public.site_settings, public.plans, public.founders to anon, authenticated;
grant select on public.profiles, public.courses, public.lessons to authenticated;
grant insert,update,delete on public.site_settings,public.plans,public.founders,public.profiles,public.courses,public.lessons to authenticated;
grant usage,select on all sequences in schema public to authenticated;

insert into storage.buckets(id,name,public) values('academy-files','academy-files',false) on conflict(id) do update set public=false;

-- Admin puede administrar todos los archivos.
drop policy if exists "admin storage all" on storage.objects;
create policy "admin storage all" on storage.objects for all to authenticated using(bucket_id='academy-files' and public.is_admin()) with check(bucket_id='academy-files' and public.is_admin());
-- Alumno puede leer objetos cuya primera carpeta coincide con su membresía.
drop policy if exists "student storage read" on storage.objects;
create policy "student storage read" on storage.objects for select to authenticated using(bucket_id='academy-files' and (storage.foldername(name))[1]=public.my_plan());

-- DESPUÉS DE CREAR TU USUARIO ADMIN EN SUPABASE AUTH, ejecuta:
-- insert into public.profiles(id,full_name,email,role,active)
-- values('UUID_DE_TU_USUARIO','Administrador','tu-correo@dominio.com','admin',true);
