import { supabase,configured } from './supabase-client.js';
import { escapeHtml,money,localMoney,waLink } from './common.js';

document.querySelector('#year').textContent=new Date().getFullYear();
const state=document.querySelector('#tradingLoginState');
function showState(msg,err=false){state.textContent=msg;state.className=`notice ${err?'error':''}`}
function youtubeId(url=''){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.split('/').filter(Boolean)[0]||'';if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||'';if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2]||'';return u.searchParams.get('v')||''}catch{return ''}}
if(!configured){showState('Supabase no está configurado.',true);throw new Error('Supabase no configurado')}
const [{data:s},{data:site}]=await Promise.all([supabase.from('trading_settings').select('*').eq('id',1).maybeSingle(),supabase.from('site_settings').select('whatsapp').eq('id',1).single()]);
if(!s){document.querySelector('#tradingWhatsapp').classList.add('hidden');document.querySelector('#tradingLoginForm').classList.add('hidden');document.querySelector('#tradingLoginTitle').textContent='Trading no disponible';document.querySelector('#tradingLoginText').textContent='Esta sección está temporalmente desactivada.';}
if(s){document.querySelector('#tradingEyebrow').textContent=s.eyebrow||'NUEVA ERA';document.querySelector('#tradingTitle').innerHTML=`${escapeHtml((s.title||'TRADING — LA ERA DIGITAL').replace(/—.*$/,'').trim())} <span>${escapeHtml((s.title||'').includes('—')?(s.title.split('—').slice(1).join('—').trim()):'LA ERA DIGITAL')}</span>`;document.querySelector('#tradingSubtitle').textContent=s.subtitle||'';document.querySelector('#tradingDescription').textContent=s.description||'';document.querySelector('#tradingPriceLocal').textContent=localMoney(s.price_local||0);document.querySelector('#tradingPriceUsd').textContent=money(s.price_usd||0,'USD');document.querySelector('#tradingLoginTitle').textContent=s.login_title||'Acceso privado Trading';document.querySelector('#tradingLoginText').textContent=s.login_text||'';document.querySelector('#tradingDisclaimer').textContent=s.disclaimer||'';if(s.cover_url)document.querySelector('#tradingHeroBg').style.backgroundImage=`url("${String(s.cover_url).replace(/["\\]/g,'')}")`;const link=waLink(s.whatsapp_number||site?.whatsapp,s.whatsapp_message||'Hola, quiero información sobre Trading — La Era Digital.');const wa=document.querySelector('#tradingWhatsapp');wa.textContent=s.button_text||'Información y pago por WhatsApp';if(link==='#'){wa.onclick=e=>{e.preventDefault();alert('Configura el WhatsApp desde Administrador.')}}else{wa.href=link;wa.target='_blank';wa.rel='noopener'}}

async function callContent(token){const r=await fetch('/.netlify/functions/trading-content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'No se pudo cargar el contenido.');return j}
function renderPrivate(data){document.querySelector('#tradingPrivate').classList.remove('hidden');document.querySelector('#tradingWelcome').textContent=`Contenido habilitado para ${data.username||'tu acceso'}`;const host=document.querySelector('#tradingResources');const items=data.resources||[];host.innerHTML=items.length?'':'<div class="notice">Todavía no hay contenido publicado en esta zona.</div>';for(const r of items){const card=document.createElement('article');card.className='trading-resource-card';let media='';if(r.resource_type==='youtube'&&r.external_url){const id=youtubeId(r.external_url);if(id)media=`<div class="youtube-embed"><iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?rel=0&modestbranding=1" title="${escapeHtml(r.title)}" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen loading="lazy"></iframe></div>`}else if(r.resource_type==='video'&&r.signed_url){media=`<video controls controlsList="nodownload" playsinline src="${escapeHtml(r.signed_url)}"></video>`}else if(r.resource_type==='image'&&r.signed_url){media=`<img src="${escapeHtml(r.signed_url)}" alt="${escapeHtml(r.title)}">`}
card.innerHTML=`${media}<div class="trading-resource-body"><span>${escapeHtml(r.resource_type.toUpperCase())}</span><h3>${escapeHtml(r.title)}</h3><p>${escapeHtml(r.description||'')}</p>${r.resource_type==='file'&&r.signed_url?`<a class="btn btn-dark btn-small" href="${escapeHtml(r.signed_url)}" target="_blank" rel="noopener">Abrir / descargar</a>`:''}${r.resource_type==='link'&&r.external_url?`<a class="btn btn-dark btn-small" href="${escapeHtml(r.external_url)}" target="_blank" rel="noopener noreferrer">Abrir recurso</a>`:''}</div>`;host.appendChild(card)}}
async function restore(){const token=sessionStorage.getItem('dwv_trading_token');if(!token)return;try{renderPrivate(await callContent(token))}catch{sessionStorage.removeItem('dwv_trading_token')}}
await restore();
document.querySelector('#tradingLoginForm').onsubmit=async e=>{e.preventDefault();showState('Verificando acceso...');try{const r=await fetch('/.netlify/functions/trading-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:document.querySelector('#tradingUser').value,password:document.querySelector('#tradingPass').value})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Acceso no válido.');sessionStorage.setItem('dwv_trading_token',j.token);showState('Acceso correcto.');renderPrivate(await callContent(j.token));document.querySelector('#tradingPrivate').scrollIntoView({behavior:'smooth'})}catch(err){showState(err.message,true)}};
document.querySelector('#tradingLogout').onclick=()=>{sessionStorage.removeItem('dwv_trading_token');document.querySelector('#tradingPrivate').classList.add('hidden');showState('Acceso Trading cerrado.')};
