import { createHmac, timingSafeEqual } from 'node:crypto';
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
function verifyToken(token,secret){try{const [body,sig]=String(token||'').split('.');if(!body||!sig)return null;const expected=createHmac('sha256',secret).update(body).digest('base64url');const a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))return null;const p=JSON.parse(Buffer.from(body,'base64url').toString());if(!p.exp||p.exp<Math.floor(Date.now()/1000))return null;return p}catch{return null}}
async function signedUrl(url,service,path){const encoded=String(path).split('/').map(encodeURIComponent).join('/');const r=await fetch(`${url}/storage/v1/object/sign/academy-files/${encoded}`,{method:'POST',headers:{apikey:service,Authorization:`Bearer ${service}`,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});if(!r.ok)return null;const j=await r.json();const s=j.signedURL||j.signedUrl||j.signed_url;if(!s)return null;return s.startsWith('http')?s:`${url}${s}`}
export default async(request)=>{
 if(request.method!=='POST')return json({error:'Método no permitido.'},405);
 const url=(process.env.SUPABASE_URL||'').replace(/\/+$/,'');const service=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!service)return json({error:'Configuración del servidor incompleta.'},500);
 let body={};try{body=await request.json()}catch{}const payload=verifyToken(body.token,service);if(!payload)return json({error:'Tu acceso Trading venció o no es válido. Ingresa nuevamente.'},401);
 const ar=await fetch(`${url}/rest/v1/trading_accounts?id=eq.${encodeURIComponent(payload.sub)}&select=id,username,active,expires_at&limit=1`,{headers:{apikey:service,Authorization:`Bearer ${service}`}});if(!ar.ok)return json({error:'No se pudo verificar el acceso.'},500);const a=(await ar.json())?.[0];if(!a||!a.active||(a.expires_at&&new Date(a.expires_at).getTime()<Date.now()))return json({error:'Este acceso está inactivo o vencido.'},403);
 const rr=await fetch(`${url}/rest/v1/trading_resources?active=eq.true&select=*&order=sort_order.asc`,{headers:{apikey:service,Authorization:`Bearer ${service}`}});if(!rr.ok)return json({error:'No se pudo cargar el contenido.'},500);const rows=await rr.json();const resources=[];for(const r of rows){const item={...r,password_hash:undefined};if(r.storage_path)item.signed_url=await signedUrl(url,service,r.storage_path);resources.push(item)}return json({username:a.username,resources});
};
